// <auto-generated />
using System;
using BookRight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRight.Infrastructure.Migrations
{
    [DbContext(typeof(BookRightDbContext))]
    [Migration("20260506103528_AddKampagner")]
    partial class AddKampagner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BehandlerBehandlingstyper", b =>
                {
                    b.Property<Guid>("BehandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BehandlingstyperBehandlingstypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BehandlerId", "BehandlingstyperBehandlingstypeId");

                    b.HasIndex("BehandlingstyperBehandlingstypeId");

                    b.ToTable("BehandlerBehandlingstyper");

                    b.HasData(
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0009-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0009-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0009-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0009-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0005-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0005-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0006-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0006-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0007-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0007-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0008-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0006-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0009-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0006-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0010-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0006-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0011-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0007-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0011-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0008-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0012-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0007-0000-0000-000000000000")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0012-0000-0000-000000000000"),
                            BehandlingstyperBehandlingstypeId = new Guid("aaaaaaaa-0008-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("BehandlerKlinikker", b =>
                {
                    b.Property<Guid>("BehandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KlinikkerKlinikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BehandlerId", "KlinikkerKlinikId");

                    b.HasIndex("KlinikkerKlinikId");

                    b.ToTable("BehandlerKlinikker");

                    b.HasData(
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0005-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0005-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0006-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0006-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0007-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0007-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0008-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0008-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0009-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0009-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0010-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0010-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0011-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0012-0000-0000-000000000000"),
                            KlinikkerKlinikId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Behandler", b =>
                {
                    b.Property<Guid>("BehandlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutorisationsNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutorisationsType")
                        .HasColumnType("int");

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BehandlerId");

                    b.ToTable("Behandlere");

                    b.HasData(
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            AutorisationsNummer = "FYS-001",
                            AutorisationsType = 0,
                            Efternavn = "Nielsen",
                            Email = "anders@bookright.dk",
                            Fornavn = "Anders",
                            Telefon = "11111101"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            AutorisationsNummer = "FYS-002",
                            AutorisationsType = 0,
                            Efternavn = "Hansen",
                            Email = "birgitte@bookright.dk",
                            Fornavn = "Birgitte",
                            Telefon = "11111102"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            AutorisationsNummer = "FYS-003",
                            AutorisationsType = 0,
                            Efternavn = "Madsen",
                            Email = "casper@bookright.dk",
                            Fornavn = "Casper",
                            Telefon = "11111103"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            AutorisationsNummer = "FYS-004",
                            AutorisationsType = 0,
                            Efternavn = "Sørensen",
                            Email = "diana@bookright.dk",
                            Fornavn = "Diana",
                            Telefon = "11111104"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0005-0000-0000-000000000000"),
                            AutorisationsNummer = "MAS-001",
                            AutorisationsType = 1,
                            Efternavn = "Christensen",
                            Email = "erik@bookright.dk",
                            Fornavn = "Erik",
                            Telefon = "11111105"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0006-0000-0000-000000000000"),
                            AutorisationsNummer = "MAS-002",
                            AutorisationsType = 1,
                            Efternavn = "Pedersen",
                            Email = "freja@bookright.dk",
                            Fornavn = "Freja",
                            Telefon = "11111106"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0007-0000-0000-000000000000"),
                            AutorisationsNummer = "MAS-003",
                            AutorisationsType = 1,
                            Efternavn = "Jensen",
                            Email = "gunnar@bookright.dk",
                            Fornavn = "Gunnar",
                            Telefon = "11111107"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0008-0000-0000-000000000000"),
                            AutorisationsNummer = "AKU-001",
                            AutorisationsType = 2,
                            Efternavn = "Larsen",
                            Email = "hanne@bookright.dk",
                            Fornavn = "Hanne",
                            Telefon = "11111108"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0009-0000-0000-000000000000"),
                            AutorisationsNummer = "AKU-002",
                            AutorisationsType = 2,
                            Efternavn = "Olsen",
                            Email = "ivan@bookright.dk",
                            Fornavn = "Ivan",
                            Telefon = "11111109"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0010-0000-0000-000000000000"),
                            AutorisationsNummer = "AKU-003",
                            AutorisationsType = 2,
                            Efternavn = "Thomsen",
                            Email = "julie@bookright.dk",
                            Fornavn = "Julie",
                            Telefon = "11111110"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0011-0000-0000-000000000000"),
                            AutorisationsNummer = "KOS-001",
                            AutorisationsType = 3,
                            Efternavn = "Andersen",
                            Email = "klaus@bookright.dk",
                            Fornavn = "Klaus",
                            Telefon = "11111111"
                        },
                        new
                        {
                            BehandlerId = new Guid("bbbbbbbb-0012-0000-0000-000000000000"),
                            AutorisationsNummer = "KOS-002",
                            AutorisationsType = 3,
                            Efternavn = "Møller",
                            Email = "laura@bookright.dk",
                            Fornavn = "Laura",
                            Telefon = "11111112"
                        });
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Behandlingstype", b =>
                {
                    b.Property<Guid>("BehandlingstypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KrævetAutorisationsType")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VarighedMinutter")
                        .HasColumnType("int");

                    b.HasKey("BehandlingstypeId");

                    b.ToTable("Behandlingstyper");

                    b.HasData(
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0001-0000-0000-000000000000"),
                            KrævetAutorisationsType = 0,
                            Navn = "Fysioterapi 30 min",
                            Pris = 395m,
                            VarighedMinutter = 30
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0002-0000-0000-000000000000"),
                            KrævetAutorisationsType = 0,
                            Navn = "Fysioterapi 45 min",
                            Pris = 589m,
                            VarighedMinutter = 45
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0003-0000-0000-000000000000"),
                            KrævetAutorisationsType = 0,
                            Navn = "Fysioterapi 60 min",
                            Pris = 745m,
                            VarighedMinutter = 60
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0004-0000-0000-000000000000"),
                            KrævetAutorisationsType = 1,
                            Navn = "Sportsmassage 30 min",
                            Pris = 350m,
                            VarighedMinutter = 30
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0005-0000-0000-000000000000"),
                            KrævetAutorisationsType = 1,
                            Navn = "Sportsmassage 60 min",
                            Pris = 699m,
                            VarighedMinutter = 60
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0006-0000-0000-000000000000"),
                            KrævetAutorisationsType = 2,
                            Navn = "Akupunktur 45 min",
                            Pris = 550m,
                            VarighedMinutter = 45
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0007-0000-0000-000000000000"),
                            KrævetAutorisationsType = 3,
                            Navn = "Kostvejledning førstegangskons.",
                            Pris = 799m,
                            VarighedMinutter = 60
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0008-0000-0000-000000000000"),
                            KrævetAutorisationsType = 3,
                            Navn = "Kostvejledning opfølgning",
                            Pris = 450m,
                            VarighedMinutter = 30
                        },
                        new
                        {
                            BehandlingstypeId = new Guid("aaaaaaaa-0009-0000-0000-000000000000"),
                            KrævetAutorisationsType = 0,
                            Navn = "Holdtræning/genoptræning",
                            Pris = 150m,
                            VarighedMinutter = 60
                        });
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnvendtRabatType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BehandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BehandlingstypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KampagneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KlinikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OprettetDen")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrisMedRabat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrisUdenRabat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("Bookinger");
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Kampagne", b =>
                {
                    b.Property<Guid>("KampagneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("GaeldendeBehandlingstyper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KampagneId");

                    b.ToTable("Kampagner");
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Klinik", b =>
                {
                    b.Property<Guid>("KlinikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AntalRum")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlinikId");

                    b.ToTable("Klinikker");

                    b.HasData(
                        new
                        {
                            KlinikId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Adresse = "Vejle Centervej 1, 7100 Vejle",
                            AntalRum = 4,
                            Navn = "BookRight Vejle"
                        },
                        new
                        {
                            KlinikId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Adresse = "Egtvedvej 5, 6040 Egtved",
                            AntalRum = 3,
                            Navn = "BookRight Egtved"
                        },
                        new
                        {
                            KlinikId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Adresse = "Kolding Storcenter 2, 6000 Kolding",
                            AntalRum = 3,
                            Navn = "BookRight Kolding"
                        });
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Kunde", b =>
                {
                    b.Property<Guid>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ForetrukkenBehandlerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fødselsdato")
                        .HasColumnType("date");

                    b.Property<string>("Helbredsnotater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loyalitetsNiveau")
                        .HasColumnType("int");

                    b.HasKey("KundeId");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("BehandlerBehandlingstyper", b =>
                {
                    b.HasOne("BookRight.Domain.Aggregates.Behandler", null)
                        .WithMany()
                        .HasForeignKey("BehandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookRight.Domain.Aggregates.Behandlingstype", null)
                        .WithMany()
                        .HasForeignKey("BehandlingstyperBehandlingstypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BehandlerKlinikker", b =>
                {
                    b.HasOne("BookRight.Domain.Aggregates.Behandler", null)
                        .WithMany()
                        .HasForeignKey("BehandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookRight.Domain.Aggregates.Klinik", null)
                        .WithMany()
                        .HasForeignKey("KlinikkerKlinikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookRight.Domain.Aggregates.Kampagne", b =>
                {
                    b.OwnsOne("BookRight.Domain.ValueObjects.KampagnePeriode", "Periode", b1 =>
                        {
                            b1.Property<Guid>("KampagneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("SlutDato")
                                .HasColumnType("date")
                                .HasColumnName("SlutDato");

                            b1.Property<DateOnly>("StartDato")
                                .HasColumnType("date")
                                .HasColumnName("StartDato");

                            b1.HasKey("KampagneId");

                            b1.ToTable("Kampagner");

                            b1.WithOwner()
                                .HasForeignKey("KampagneId");
                        });

                    b.OwnsOne("BookRight.Domain.ValueObjects.RabatProcent", "Rabatprocent", b1 =>
                        {
                            b1.Property<Guid>("KampagneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RabatProcent");

                            b1.HasKey("KampagneId");

                            b1.ToTable("Kampagner");

                            b1.WithOwner()
                                .HasForeignKey("KampagneId");
                        });

                    b.Navigation("Periode")
                        .IsRequired();

                    b.Navigation("Rabatprocent")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
